### ISSUE TITLE
Example from the tutorial: predict(OLS, newX, :confint) fails

### ISSUE THREAD

**Issue by HamletFr** [JuliaStats/GLM.jl#214] opened 2018-02-09 16:42 UTC
Hi,

when I try to rebuild the minimal examples I get with: predict(OLS, newX, :confint) the following error message:

MethodError: no method matching predict(::GLM.GeneralizedLinearModel{GLM.GlmResp{Array{Float64,1},Distributions.Normal{Float64},GLM.IdentityLink},GLM.DensePredChol{Float64,Base.LinAlg.Cholesky{Float64,Array{Float64,2}}}}, ::DataFrames.DataFrame, ::Symbol)

Is the example not working any longer?

Best regards!

**Comment by nalimilan** [comment] 2018-02-09 16:55
Duplicate of https://github.com/JuliaStats/GLM.jl/issues/174. We should probably remove this example since we haven't implemented the corresponding feature since last year.

**Closed by nalimilan** 2018-02-09 16:55 UTC
