### ISSUE TITLE
No method matching predict

### ISSUE THREAD

**Issue by mthorrell** [JuliaStats/GLM.jl#174] opened 2017-02-10 04:31 UTC
I'm new to Julia, so I may be doing something wrong. But the following code pulled basically straight from the example on Github doesn't run for me.

```
using GLM
using DataFrames
data = DataFrame(X=[1,2,3], Y=[2,4,7])
OLS = glm(Y ~ X, data, Normal(), IdentityLink())
newX = DataFrame(X=[2,3,4])
predict(OLS, newX, :confint)
```

I get
```
ERROR: MethodError: no method matching predict(::GLM.GeneralizedLinearModel{GLM.GlmResp{Array{Float64,1},Distributions.Normal{Float64},GLM.IdentityLink},GLM.DensePredChol{Float64,Base.LinAlg.Cholesky{Float64,Array{Float64,2}}}}, ::DataFrames.DataFrame, ::Symbol)
Closest candidates are:
  predict(::DataFrames.DataFrameRegressionModel{M,T}, ::Any...; kwargs...)
...
```
This also occurs if I remove `:confint`.

**Comment by nalimilan** [comment] 2017-02-10 09:16
`:confint` isn't supported yet when passing a `DataFrame` (cf. https://github.com/JuliaStats/GLM.jl/pull/171). I don't get an error if I remove that argument. Can you post the error you get in that case?

**Comment by mthorrell** [comment] 2017-02-10 14:13
Interesting, it does work for me now.

In any case, this is on the GLM Github homepage (https://github.com/JuliaStats/GLM.jl). Perhaps that should be edited?

```
 julia> newX = DataFrame(X=[2,3,4]);
 julia> predict(OLS, newX, :confint)
```

**Comment by nalimilan** [comment] 2017-02-10 14:40
Right, that was introduced a little too early in https://github.com/JuliaStats/GLM.jl/pull/171.

@mkborregaard We should either add support for this in DataFrames soon, or revert that addition temporarily. What do you think?

**Comment by mkborregaard** [comment] 2017-02-10 14:41
Are you asking me to add it to DataFrames? I might be able to find the time, but I didn't have a look at the DataFrames code for this yet.

**Comment by mkborregaard** [comment] 2017-02-10 14:43
Note also that this is presently only implemented for lm, so glm would also have to be implemented

**Comment by nalimilan** [comment] 2017-02-10 14:43
Adding this should be pretty easy, you just need to adapt the signature in `src/statmodels/statsmodel.jl`. Else, just revert that example in README.

**Comment by mkborregaard** [comment] 2017-02-10 14:47
Alright, I will take one of these actions within the week(-end hopefully).

**Comment by mkborregaard** [comment] 2017-02-12 20:57
https://github.com/JuliaStats/DataFrames.jl/pull/1160

**Comment by mkborregaard** [comment] 2017-02-12 21:07
That only fixes the method that supplies newX. I can't seem to work out where `predict` without newX is located? That should also have a method with confidence intervals. Thanks.

**Comment by nalimilan** [comment] 2017-02-13 09:36
It's defined via `@delegate`: https://github.com/mkborregaard/DataFrames.jl/blob/bb8c64a9b8e56e2ad40ba80d151fb36df14090ca/src/statsmodels/statsmodel.jl#L68 AFAICT it should redirect `predict(m::DataFrameRegressionModel, interval_type, level)` to `predict(m::StatModel, interval_type, level)`. Doesn't it?

**Comment by mkborregaard** [comment] 2017-02-13 09:39
I'll define that function for GLM and see if it works :-)

**Comment by mkborregaard** [comment] 2017-02-13 09:41
It was just that in GLM I could only find it defined for LinPredModel

**Comment by findmyway** [comment] 2017-12-28 14:10
So any update here?

**Comment by mkborregaard** [comment] 2018-01-02 08:53
My bad conscience comes back to bite me. I had a working PR ( https://github.com/JuliaData/DataFrames.jl/pull/1160 ) but then never added the extra tests necessary for merging. I'll see if it isn't easy to rebase on current master.

**Comment by andreasnoack** [comment] 2024-11-20 13:56
This now works so closing
```julia
julia> DataFrame(predict(OLS, newX, interval = :confidence))
3×3 DataFrame
 Row │ prediction  lower     upper
     │ Float64?    Float64?  Float64?
─────┼────────────────────────────────
   1 │    4.33333   3.87137   4.7953
   2 │    6.83333   6.1029    7.56377
   3 │    9.33333   8.11108  10.5556
```
@nalimilan do you recall or can point me to a discussion of why `predict` doesn't return `DataFrame`. Is it to be more "Tables generic"

**Closed by andreasnoack** 2024-11-20 13:56 UTC

**Comment by nalimilan** [comment] 2024-11-20 14:04
Yeah, that's because we don't want GLM to depend on DataFrames. I guess it would be possible to keep track of the type of table that was used when fitting, and return the result in that type (which works even without a dependency). But currently we don't do that. Could be added to the list of 2.0 changes...
