### ISSUE TITLE
lm does not work with Float32

### ISSUE THREAD

**Issue by kingjosephm** [JuliaStats/GLM.jl#403] opened 2021-02-09 15:26 UTC
```julia
julia> using DataFrames, GLM, Pkg

julia> Pkg.status("GLM")
Status `C:\Users\jking\.julia\environments\v1.5\Project.toml`
  [38e38edf] GLM v1.3.11

julia> Pkg.status("DataFrames")
Status `C:\Users\jking\.julia\environments\v1.5\Project.toml`
  [a93c6f00] DataFrames v0.21.8

julia> df = DataFrame(rand(Float32, (100, 2)))
100×2 DataFrame
│ Row │ x1       │ x2       │
│     │ Float32  │ Float32  │
├─────┼──────────┼──────────┤
│ 1   │ 0.761121 │ 0.593105 │
│ 2   │ 0.174233 │ 0.625339 │
⋮
│ 98  │ 0.621827 │ 0.485921 │
│ 99  │ 0.340933 │ 0.130693 │
│ 100 │ 0.78795  │ 0.380114 │

julia> ols = lm(@formula(x1 ~ x2), df)
ERROR: MethodError: no method matching delbeta!(::GLM.DensePredChol{Float64,LinearAlgebra.Cholesky{Float64,Array{Float64,2}}}, ::Array{Float32,1})
Closest candidates are:
  delbeta!(::GLM.DensePredQR{T}, ::Array{T,1}) where T<:Union{Float32, Float64} at C:\Users\jking\.julia\packages\GLM\dbJFe\src\linpred.jl:75
  delbeta!(::GLM.DensePredChol{T,var"#s19"} where var"#s19"<:LinearAlgebra.Cholesky, ::Array{T,1}) where T<:Union{Float32, Float64} at C:\Users\jking\.julia\packages\GLM\dbJFe\src\linpred.jl:129
  delbeta!(::GLM.DensePredChol{T,var"#s19"} where var"#s19"<:LinearAlgebra.CholeskyPivoted, ::Array{T,1}) where T<:Union{Float32, Float64} at C:\Users\jking\.julia\packages\GLM\dbJFe\src\linpred.jl:134
  ...
Stacktrace:
 [1] fit!(::LinearModel{GLM.LmResp{Array{Float32,1}},GLM.DensePredChol{Float64,LinearAlgebra.Cholesky{Float64,Array{Float64,2}}}}) at C:\Users\jking\.julia\packages\GLM\dbJFe\src\lm.jl:116
 [2] fit(::Type{LinearModel}, ::Array{Float64,2}, ::Array{Float32,1}, ::Bool; wts::Array{Float32,1}) at C:\Users\jking\.julia\packages\GLM\dbJFe\src\lm.jl:127
 [3] fit(::Type{LinearModel}, ::Array{Float64,2}, ::Array{Float32,1}, ::Bool) at C:\Users\jking\.julia\packages\GLM\dbJFe\src\lm.jl:127
 [4] fit(::Type{LinearModel}, ::FormulaTerm{Term,Term}, ::DataFrame, ::Bool; contrasts::Dict{Symbol,Any}, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{,Tuple{}}}) at C:\Users\jking\.julia\packages\StatsModels\rlTon\src\statsmodel.jl:88
 [5] fit at C:\Users\jking\.julia\packages\StatsModels\rlTon\src\statsmodel.jl:82 [inlined]
 [6] #lm#2 at C:\Users\jking\.julia\packages\GLM\dbJFe\src\lm.jl:144 [inlined]
 [7] lm at C:\Users\jking\.julia\packages\GLM\dbJFe\src\lm.jl:144 [inlined] (repeats 2 times)
 [8] top-level scope at REPL[5]:1
```

**Comment by nalimilan** [comment] 2021-02-14 15:55
Duplicate of https://github.com/JuliaStats/GLM.jl/issues/260.

**Closed by nalimilan** 2021-02-14 15:55 UTC
