### ISSUE TITLE
julia quits when using GLM with large sparse matrix

### ISSUE THREAD

**Issue by jotwin** [JuliaStats/GLM.jl#133] opened 2016-03-18 20:45 UTC
This works
```
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.2 (2015-12-06 21:47 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org release
|__/                   |  x86_64-linux-gnu
using GLM
x = sparse(rand(Bernoulli(.05), 1000, 10))
y = rand(Poisson(100), 1000)
fit(GeneralizedLinearModel, x, y, Poisson())
GLM.GeneralizedLinearModel{GLM.GlmResp{Array{Float64,1},Distributions.Poisson,GLM.LogLink},GLM.SparsePredChol{Float64,SparseMatrixCSC{Float64,Int64},Base.SparseMatrix.CHOLMOD.Factor{Float64}}}:

Coefficients:
     Estimate Std.Error z value Pr(>|z|)
x1    1.84329 0.0172444 106.892   <1e-99
x2    1.58139 0.0169282 93.4178   <1e-99
x3    1.93437 0.0197689 97.8496   <1e-99
x4    3.26923 0.0133687 244.544   <1e-99
x5    2.12233 0.0176871 119.993   <1e-99
x6    2.07031 0.0170098 121.713   <1e-99
x7    2.87732 0.0173352 165.981   <1e-99
x8    1.68784 0.0158358 106.584   <1e-99
x9    2.24792 0.0174175 129.061   <1e-99
x10   2.98066 0.0148215 201.104   <1e-99

```
This also works

```
x = rand(Bernoulli(.05), 100000, 100)
y = rand(Poisson(100), 100000)
fit(GeneralizedLinearModel, x, y, Poisson())

```

This makes julia die, as in completely quits.
```

x = sparse(rand(Bernoulli(.05), 100000, 100))
y = rand(Poisson(100), 100000)
fit(GeneralizedLinearModel, x, y, Poisson())
julia: symbol lookup error: /usr/bin/../lib/x86_64-linux-gnu/julia/libcholmod.so: undefined symbol: dpotrf_
```

**Comment by nalimilan** [comment] 2016-03-18 20:56
It works here with 0.5 built from source as well as from the Fedora RPM. Are you using Julia from the PPA? On what distribution release? Another user has reported this problem before: https://groups.google.com/forum/#!topic/julia-stats/36SGYDyuilo

**Comment by dmbates** [comment] 2016-03-18 20:58
There is a problem with the installation of Julia.  The CHOLMOD library, libcholmod.so, is not linked to an appropriate LAPACK.  The problem is not specific to GLM, it will occur any time you try to `cholfact` a positive-definite symmetric sparse matrix.

**Comment by jotwin** [comment] 2016-03-18 21:03
Its from the official repo, ubuntu 14.04

julia> versioninfo()
Julia Version 0.4.2
Commit bb73f34 (2015-12-06 21:47 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2430 0 @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by KristofferC** [comment] 2016-03-18 21:18
`NO_LAPACK` looks ominous

**Comment by nalimilan** [comment] 2016-03-18 21:33
The PPA is unmaintained at the moment due to lack of manpower, and it will probably be removed from the Downloads page soon. See https://github.com/JuliaLang/julia/issues/15297. You'd better use the generic binary tarballs for Linux instead.

I'm closing this issue, since it's not particular to GLM.jl, but feel free to subscribe to the other one.

**Closed by nalimilan** 2016-03-18 21:33 UTC

**Comment by ViralBShah** [comment] 2016-03-19 16:37
I think the ppa needs to be removed right away. I run into far too many people who get into trouble because of it.
